# Generated by Django 5.2.7 on 2026-03-16 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="stripe_payment_intent",
            new_name="stripe_checkout_session",
        ),
    ]
